TRAIN:
    model: resnet101BNET
    workers: 3
    batch_size: 256
    epochs: 100

    lr_mode : step
    base_lr: 0.1
    decay_factor : 0.1
    step : 30,60,90

    momentum: 0.9
    weight_decay: 0.0001

    using_moving_average : True
    last_gamma : True
    using_bn: True

    stop: True
    print_freq: 100
    model_dir: checkpoint/resnet101BNET-3

    train_root: ../../data/train
    train_source: ../data/train.txt
    val_root: ../../data/val
    val_source: ../data/val.txt

TEST:
    checkpoint_path : R101_BNET-3.pth
